// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn072t0a3h0AmDoe1RKvwGbzn1EnMnCTY',
    appId: '1:483807574554:web:3019c5783905ce4134efa3',
    messagingSenderId: '483807574554',
    projectId: 'noun-the-wiser-ai',
    authDomain: 'noun-the-wiser-ai.firebaseapp.com',
    storageBucket: 'noun-the-wiser-ai.firebasestorage.app',
    measurementId: 'G-B995ES1VFN',
  );

  // You can get these values from your Firebase Console

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1qEkpWUXDT1cqc3yo52Wqhn7lZjYJ9g',
    appId: '1:483807574554:android:aca07d6a43da638b34efa3',
    messagingSenderId: '483807574554',
    projectId: 'noun-the-wiser-ai',
    storageBucket: 'noun-the-wiser-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNr6wUAXGG8FUxt9UEVKb_S8l1-BGtJA',
    appId: '1:483807574554:ios:2ca5a1097af02e3734efa3',
    messagingSenderId: '483807574554',
    projectId: 'noun-the-wiser-ai',
    storageBucket: 'noun-the-wiser-ai.firebasestorage.app',
    iosBundleId: 'com.clawworks.nounTheWiser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: 'your-macos-client-id',
    iosBundleId: 'com.example.nounTheWiser',
  );
}